#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_hl2_formats = env_modules.Clone()
env_hl2_formats.add_source_files(env.modules_sources, "*.cpp")

if env["tests"]:
    env_hl2_formats.add_source_files(env.modules_sources, "./tests/*.cpp")
